name: My Conditional Workflow
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      proceed_flag:
        description: "Proceed with subsequent steps?"
        required: true
        type: boolean
        default: false  # Optional default value

jobs:
  check_and_proceed:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo This runs all the time

      - name: Conditional execution
        if: ${{ github.event.inputs.proceed_flag == 'true' }}
        run: |
          echo This is true statement

      - name: Terminate if input is 'false'
        if: ${{ github.event.inputs.proceed_flag == 'false' }}
        run: |
          echo This is false statement
