name: Example Workflow

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run commands
        run: echo "Executing commands..."

      - name: Example Step
        if: ${{ github.event.inputs.proceed == 'true' }}
        run: echo "Proceeding with further steps..."

      - name: Stop the process
        if: ${{ github.event.inputs.proceed != 'true' }}
        run: echo "Stopping the process because input is not true..."
