name: Example GitHub Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    inputs:
      proceed: 
        description: 'Proceed with further steps?'
        required: true
        default: 'false'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run commands
      run: |
        echo "Executing commands..."

    - name: Check input and proceed
      if: ${{ github.event.inputs.proceed == 'true' }}
      run: |
        # Add further steps to execute if the input is true
        echo "Proceeding with further steps..."
      
    - name: Stop the process
      if: ${{ github.event.inputs.proceed != 'true' }}
      run: |
        # Add any necessary steps to stop the process
        echo "Stopping the process because input is not true..."
        exit 1
